package net.haitham.otloblidal.entity.annotation;
// Generated Jan 10, 2020 8:49:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AdminUser generated by hbm2java
 */
@Entity
@Table(name="admin_user"
    ,catalog="online_ordering_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class AdminUser  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String hash;
     private byte active;
     private String originalPassword;

    public AdminUser() {
    }

    public AdminUser(String username, String password, byte active,String email,String hash,String originalPassword) {
       this.username = username;
       this.password = password;
       this.active = active;
       this.email=email;
       this.hash = hash;
       this.originalPassword = originalPassword;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="active", nullable=false)
    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }
    @Column(name="email", nullable=false)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Column(name="hash", nullable=false)
    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }
    @Column(name="original_password", nullable=false)
    public String getOriginalPassword() {
        return originalPassword;
    }

    public void setOriginalPassword(String originalPassword) {
        this.originalPassword = originalPassword;
    }




}


