package net.haitham.otloblidal.entity.annotation;
// Generated Jan 10, 2020 8:49:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="online_ordering_db"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name_ar"), @UniqueConstraint(columnNames="name_en")} 
)
public class City  implements java.io.Serializable {


     private Integer id;
     private Country country;
     private String nameAr;
     private String nameEn;
     private Set<Area> areas = new HashSet<Area>(0);

    public City() {
    }

	
    public City(Country country, String nameAr, String nameEn) {
        this.country = country;
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public City(Country country, String nameAr, String nameEn, Set<Area> areas) {
       this.country = country;
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.areas = areas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
@LazyCollection(LazyCollectionOption.TRUE)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="name_ar", unique=true, nullable=false, length=100)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", unique=true, nullable=false, length=100)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

@OneToMany(cascade = CascadeType.ALL ,fetch=FetchType.LAZY, mappedBy="city")
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }




}


